Modul6/Moodul5/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware('auth')->group(function(){
        Route::resource('users','UserController');
        Route::get('post/{id}/like','PostController@addLike')->name('post.addlike');
        Route::resource('post', 'PostController');
        Route::group(['as'=>'post.','prefix'=>'post/{pid}/'], function(){
            Route::resource('comment', 'KomentarPostController');
        });
        // Route::get('post/{id}/comment','KomentarPostController@addComment')->name('comment.addComment');
});


Route::get('/home', 'HomeController@index')->name('home');

Modul6/Moodul5/resources/views/detail.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-5">
            <img src="{{asset($post->image)}}" width="100%">
        </div>
        <div class="col-md-5">
            <img src="{{ asset($user->avatar) }}" width="50" style="border-radius: 50%; border: solid 1px;">
            <b>{{$user->name}}</b> <br>
            <hr>
            <p><b>{{$user->email}}</b> {{$post->caption}}</p>
            <p>
                @foreach($comments as $komentar)
                <b>{{$komentar->user()->first()->email}}</b> {{$komentar->comment}} <br>
                @endforeach
            </p>
            <hr>
            <form class="btn" method=GET action="{{url('/post/'.$post->id.'/like')}}">
                <button class="btn"><i class="far fa-heart" style='font-size:17px'></i></button>    
                </form>    
                <button class="btn"><i class='far fa-comment' style='font-size:17px'></i></button>
                 <br>
                <label style="margin-top:5px; margin-bottom:5">{{$post->likes}} likes</label>
                </form>
                <br>
            
            <form class="btn" method=POST action="{{route('post.comment.store', [$post->id])}}">
                @csrf
                <div class="input-group mb-3">
                <input type="text" class="form-control" placeholder="Komen" name="comment">
                <div class="input-group-append">
                <span class="input-group-text"><button class="btn" type="submit">Post</button></span>
                </div>
                </div>
                </form>
        </div>
    </div>
</div>
@endsection

Modul6/Moodul5/resources/views/editprofile.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
<div class="row justify-content-center">
    <div class="col-md-6">
    <h1>Edit Profile</h1>
    <br>
    <form method="post" action="{{route('users.update',[$user->id])}}" enctype="multipart/form-data">
    @csrf
        <p style="margin-bottom:5px; margin-left:5px; ">Title</p>
        <input type="text" class="form-control" name="title" placeholder="Insert a Title"><br>
        <p style="margin-bottom:5px; margin-left:5px; margin-top:10px;">Description</p>
        <input type="text" class="form-control" name="description" placeholder="Insert a Description"><br>
        <p style="margin-bottom:5px; margin-left:5px; margin-top:10px;">URL</p>
        <input type="text" class="form-control" name="url" placeholder="Insert a Description"><br>
        <p style="margin-bottom:5px; margin-left:5px; margin-top:10px;">Profile Image</p>
        <input type="file" name="avatar" placeholder="image" style="margin-bottom:35px;"><br>
        <input type="hidden" value="PUT" name="_method">
        <input type="submit" value="Save Profile" style="background-color:#29B4F0; border-color:#DEDEDE ; color:white; border-radius:5px;   ">
    </form>
</div>
</div>
</div>
@endsection

Modul6/Moodul5/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
@foreach ($posts as $post)
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                
                <div class="card-header"><img src="{{ $user->avatar }}" width="7%" style="border-radius:50%; margin-right:10px;">{{ $user->name }}</div>
                
                <div class="card-body" style="padding:0;">
                <a href="{{route('post.show',[$post->id])}}"><img src="{{ $post->image }}" width="100%" name="image" ></a>
                </div>
                <div class="card-footer">
                <form class="btn" method=GET action="{{url('/post/'.$post->id.'/like')}}">
                <button class="btn"><i class="far fa-heart" style='font-size:17px'></i></button>    
                </form>    
                <button class="btn"><i class='far fa-comment' style='font-size:17px'></i></button>
                 <br>
                <label style="margin-top:5px; margin-bottom:5">{{$post->likes}} likes</label>
                <br>
                <label ><b>{{ $user->email }}</b></label>
                <label>{{ $post->caption }}</label>
                <br>
                <form class="btn" method=POST action="{{route('post.comment.store', [$post->id])}}">
                @csrf
                <div class="input-group mb-3">
                <input type="text" class="form-control" placeholder="Komen" name="comment" style="padding:12px 16px">
                <div class="input-group-append">
                <span class="input-group-text"><button class="btn" type="submit">Post</button></span>
                </div>
                </div>
                </form>
                </div> 
            </div>
        </div>
    </div>
    <br>
    @endforeach
</div>
@endsection

Modul6/Moodul5/resources/views/newpost.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
<div class="row justify-content-center">
    <div class="col-md-6">
    <h1>Add New Post</h1>
    <br>
    <form method="post" action="{{route('users.store')}}" enctype="multipart/form-data">
    @csrf
        <p style="margin-bottom:5px; margin-left:5px">Post caption</p>
        <input type="text" class="form-control" name="caption" placeholder="Insert a Caption" ><br>
        <p style="margin-bottom:5px; margin-left:5px">Post image</p>
        <input type="file" name="image" placeholder="image" style="margin-bottom:35px;"><br>
        <input type="submit" value="Add new post" style="background-color:#29B4F0; border-color:#DEDEDE ; color:white; border-radius:5px; padding:6px 16px;">
    </form>
</div>
</div>
</div>
@endsection

Modul6/Moodul5/resources/views/profile.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center my-5">
        <div class="col-md-4 text-center">
            <img src="{{ asset($user->avatar) }}" style="heigth:300px; width:300px;">
        </div>
        <div class="col-md-6">
            <h4>{{$user->name}}</h4><br>
            <p><a href="{{route('users.edit',[$user->id])}}" >Edit Profile</a><br>
                <b>{{sizeof($posts)}}</b> Post</p>
            <p><b>{{$user->title}}</b><br>{{$user->description}}<br><a href="{{$user->url}}">{{$user->url}}</a> 
            </p>
        </div>
        <div class="col-md-2 text-right">
            <a href="{{route('post.create')}}">Add New Post</a>
        </div>
    </div>
    <div class="row justify-content-left my-1">
    @foreach($posts as $post)
        <div class="col-md-4 my-3">
            <a href="{{route('post.show',[$post->id])}}"><img src="{{asset($post->image)}}" style="width:100%"></a>
        </div>
        @endforeach
    </div>
</div>
@endsection